#define LOOKUP_FIRST_LEVEL_SHIFT 12
#define LOOKUP_FIRST_LEVEL_MASK ((1<<20) - 1) 
#define LOOKUP_SECOND_LEVEL_SHIFT 4 
#define LOOKUP_SECOND_LEVEL_MASK ((1<<8) - 1) 
#define LOOKUP_THIRD_LEVEL_SHIFT 0 
#define LOOKUP_THIRD_LEVEL_MASK ((1<<4) - 1)

#define LOOKUP_SECOND_LEVEL_BASE ((1<<20) << 2) 
#define LOOKUP_THIRD_LEVEL_BASE LOOKUP_SECOND_LEVEL_BASE +((1<<4) << 4) 

#define LOOKUP_SECOND_LEVEL_CHUNK_SIZE_LOG	4
#define LOOKUP_THIRD_LEVEL_CHUNK_SIZE_LOG	8

