// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.2
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module types_float_double_grp_fu_100_ACMP_dsqrt_4_io(
    clk,
    reset,
    io_ce,
    io_rdy,
    io_a,
    io_b,
    io_result);

input clk;
input reset;
input io_ce;
output io_rdy;
input[64 - 1:0] io_a;
input[64 - 1:0] io_b;
output[64 - 1:0] io_result;

sqrt64fp m(
    .clk(clk),
    .ce(io_ce),
    .rdy(io_rdy),
    .a(io_a),
    .result(io_result));


endmodule

module sqrt64fp(
    clk,
    ce,
    rdy,
    a,
    result);

input clk;
input ce;
output rdy;
input[64 - 1:0] a;
output[64 - 1:0] result;


//assign result = a + b;
//ACMP_ddiv #(
//.ID( ID ),
//.NUM_STAGE( 59 ),
//.din0_WIDTH( din0_WIDTH ),
//.din1_WIDTH( din1_WIDTH ),
//.dout_WIDTH( dout_WIDTH ))
//ACMP_ddiv_U(
//    .clk( clk ),
//    .reset( reset ),
//    .ce( ce ),
//    .din0( din0 ),
//    .din1( din1 ),
//    .dout( dout ));

endmodule
