#define NUM_OF_CACHE_MISS_PIPE_STAGES  2
#define BURST_FACTOR  1
#define FIXED_FANOUT  1
#define AVERAGE_FANOUT  5
#define uwThreads  2
#define ugThreads  2
#define addPipelined  false
#define mulPipelined  false
#define divPipelined  false
#define rcPipelined  false
#define sharedRc  false
#define sharedRa  false
#define ugRepFactor  2
#define uwRepFactor  4
#define numOfCacheThreads  3
#define cacheHeightLog  7
#define llCacheHeightLog  7
#define cacheLineSizeLog  4
